# TFSec Configuration for ROSA Classic GovCloud

# Minimum severity level
minimum_severity: MEDIUM

# Exclude specific checks that conflict with ROSA requirements
# Each exclusion includes justification for compliance auditing
exclude:
  # ROSA requires specific IAM role configurations with wildcards for operator roles
  - aws-iam-no-policy-wildcards

  # ROSA Classic requires unrestricted egress to Red Hat services (quay.io,
  # registry.redhat.io, sso.redhat.com, etc.) which use dynamic IPs/CDNs.
  # Cluster runs in private subnets; egress goes through NAT gateways.
  # See: https://docs.openshift.com/rosa/rosa_install_access_delete_clusters/rosa_getting_started_iam/rosa-aws-prereqs.html
  - aws-vpc-no-public-egress-sgr
  - aws-ec2-no-public-egress-sgr

# Include additional checks
include: []

# Severity overrides
severity_overrides:
  # Downgrade non-critical findings
  aws-ec2-enforce-http-token-imds: LOW

# Custom check paths
custom_check_dir: ""

# Output format
format: default

# Ignore file patterns
ignore-hcl-files: []
