# OpenShift Virtualization Operator Subscription
#
# Installs the OpenShift Virtualization (KubeVirt) Operator from OperatorHub.
#
# Note: This is a reference file. Terraform uses the .yaml.tftpl template
# in this directory to install the operator via kubectl_manifest.
#
# Channel: stable auto-selects appropriate version for OCP release
#
# IMPORTANT: Requires bare metal instances (.metal instance types)
# for hardware virtualization support.
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  channel: stable
  name: kubevirt-hyperconverged
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
