# Loki Operator Subscription
#
# Installs the Loki Operator from OperatorHub.
#
# IMPORTANT: Channel selection depends on OpenShift version:
# - stable-6.2: OpenShift 4.16, 4.17, 4.18 (GovCloud)
# - stable-6.4: OpenShift 4.19+ (Commercial HCP)
#
# Terraform automatically selects the correct channel based on
# openshift_version when deploying this operator.
#
# The Loki Operator manages:
# - LokiStack custom resource
# - Loki components (distributor, ingester, querier, compactor, etc.)
# - S3 storage integration
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: loki-operator
  namespace: openshift-logging
spec:
  # Default: stable-6.4 for OCP 4.19+
  # Change to stable-6.2 for OCP 4.16-4.18 (GovCloud)
  channel: stable-6.4
  installPlanApproval: Automatic
  name: loki-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
